spring:
  main:
    web-application-type: none
  application:
    name: 'AIS "Bouncing"'
  datasource:
    url: jdbc:h2:file:./h2db/bouncing
    driver-class-name: org.h2.Driver
    username: sa
    continue-on-error: true
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: h2